### ISSUE TITLE
IMPORT FAILED after the new update

### ISSUE THREAD

**Issue by anseltrust** [yolain/ComfyUI-Easy-Use#568]
I need some help, the node is not working after the update. Manually downloading didn't solve the problem as well.

here is my pip list and log;

C:\Comfy\ComfyUI_windows_portable\ComfyUI>pip list
Package                           Version
--------------------------------- --------------
absl-py                           2.1.0
accelerate                        1.1.1
addict                            2.4.0
aiofiles                          23.2.1
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioresponses                      0.7.6
aiosignal                         1.3.1
albucore                          0.0.15
albumentations                    1.4.10
altair                            5.4.1
annotated-types                   0.7.0
anthropic                         0.34.2
anyio                             4.4.0
appdirs                           1.4.4
APScheduler                       3.10.1
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
asttokens                         2.4.1
astunparse                        1.6.3
async-lru                         2.0.4
async-timeout                     4.0.3
attrs                             24.2.0
awscli                            1.33.44
babel                             2.16.0
backoff                           2.2.1
beautifulsoup4                    4.12.3
bleach                            6.1.0
boto3                             1.34.123
botocore                          1.34.162
cachetools                        5.5.0
certifi                           2024.2.2
cffi                              1.17.1
charset-normalizer                3.3.2
click                             8.1.7
clip                              1.0
clip-interrogator                 0.6.0
colorama                          0.4.4
coloredlogs                       15.0.1
comm                              0.2.2
contourpy                         1.2.0
cryptography                      43.0.1
customtkinter                     5.2.2
cycler                            0.12.1
Cython                            3.0.0
darkdetect                        0.8.0
dataclasses-json                  0.6.7
debugpy                           1.8.7
decorator                         5.1.1
defusedxml                        0.7.1
diffusers                         0.31.0
dill                              0.3.6
distro                            1.9.0
dlib                              19.24.1
docker                            6.1.3
docker-pycreds                    0.4.0
docstring_parser                  0.16
docutils                          0.16
easydict                          1.13
einops                            0.8.0
exceptiongroup                    1.2.2
executing                         2.1.0
face-alignment                    1.3.4
fastapi                           0.110.3
fastcluster                       1.2.6
fastjsonschema                    2.20.0
ffmpeg-python                     0.2.0
ffmpy                             0.4.0
filelock                          3.13.1
flatbuffers                       24.3.25
fonttools                         4.50.0
fqdn                              1.5.1
frozenlist                        1.4.1
fsspec                            2024.9.0
ftfy                              6.2.0
future                            1.0.0
gast                              0.4.0
gdown                             3.12.2
gitdb                             4.0.11
GitPython                         3.1.42
google-api-core                   2.19.2
google-api-python-client          2.146.0
google-auth                       2.34.0
google-auth-httplib2              0.2.0
google-auth-oauthlib              0.4.6
google-cloud-core                 2.4.1
google-cloud-storage              2.18.2
google-crc32c                     1.6.0
google-pasta                      0.2.0
google-resumable-media            2.7.2
googleapis-common-protos          1.65.0
GPUtil                            1.4.0
gradio                            4.44.0
gradio_client                     1.3.0
grpcio                            1.66.1
h11                               0.14.0
h5py                              3.11.0
httpcore                          1.0.5
httplib2                          0.22.0
httpx                             0.27.2
huggingface-hub                   0.24.7
humanfriendly                     10.0
idna                              3.6
imageio                           2.34.2
imageio-ffmpeg                    0.5.1
importlib_metadata                8.5.0
importlib_resources               6.4.5
inference-cli                     0.18.0
inference-gpu                     0.19.0
iniconfig                         2.0.0
insightface                       0.7.3
ipykernel                         6.29.5
ipython                           8.28.0
ipywidgets                        8.1.5
isoduration                       20.11.0
jax                               0.4.30
jaxlib                            0.4.30
jedi                              0.19.1
Jinja2                            3.1.4
jiter                             0.5.0
jmespath                          1.0.1
joblib                            1.2.0
json5                             0.9.25
jsonpointer                       3.0.0
jsonschema                        4.23.0
jsonschema-specifications         2023.12.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.5
jupyter_server                    2.14.2
jupyter_server_terminals          0.5.3
jupyterlab                        4.2.5
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.13
keras                             2.10.0
Keras-Preprocessing               1.1.2
kiwisolver                        1.4.5
lab                               8.2
lark-parser                       0.12.0
lazy_loader                       0.4
libclang                          18.1.1
llvmlite                          0.42.0
lmdb                              1.4.1
Markdown                          3.7
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
marshmallow                       3.22.0
matplotlib                        3.9.0
matplotlib-inline                 0.1.7
mdurl                             0.1.2
mistune                           3.0.2
ml-dtypes                         0.4.0
mpmath                            1.3.0
multidict                         6.1.0
mypy-extensions                   1.0.0
narwhals                          1.8.1
nbclient                          0.10.0
nbconvert                         7.16.4
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.2.1
notebook                          7.2.2
notebook_shim                     0.2.4
numba                             0.59.1
numexpr                           2.10.1
numpy                             1.24.4
nvidia-cuda-runtime-cu11          11.8.89
nvidia-cuda-runtime-cu12          12.6.68
nvidia-ml-py                      12.560.30
oauthlib                          3.2.2
onnx                              1.14.0
onnxruntime                       1.19.2
onnxruntime-gpu                   1.15.0
open_clip_torch                   2.29.0
openai                            1.46.0
opencv-contrib-python             4.10.0.84
opencv-python                     4.10.0.84
opencv-python-headless            4.10.0.84
opt-einsum                        3.3.0
orjson                            3.10.7
overrides                         7.7.0
packaging                         24.1
pandas                            2.0.1
pandocfilters                     1.5.1
parso                             0.8.4
pathtools                         0.1.2
pendulum                          3.0.0
piexif                            1.1.3
Pillow                            9.5.0
pip                               24.3.1
platformdirs                      4.3.6
pluggy                            1.5.0
prettytable                       3.11.0
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 6.0.0
prompt_toolkit                    3.0.48
proto-plus                        1.24.0
protobuf                          4.23.2
psutil                            6.0.0
PuLP                              2.9.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyasn1                            0.6.1
pyasn1_modules                    0.4.1
pybase64                          1.4.0
pycparser                         2.22
pydantic                          2.9.1
pydantic_core                     2.23.3
pydantic-settings                 2.5.2
pydot                             3.0.1
pydub                             0.25.1
Pygments                          2.18.0
pykalman                          0.9.7
pyparsing                         3.1.2
pyreadline3                       3.5.2
PySocks                           1.7.1
pytest                            8.3.3
pytest-asyncio                    0.21.1
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-json-logger                2.0.7
python-multipart                  0.0.9
pytube                            15.0.0
pytz                              2024.1
pyvirtualcam                      0.11.1
PyWavelets                        1.7.0
pywin32                           306
pywinpty                          2.0.13
PyYAML                            6.0.1
pyzmq                             26.2.0
redis                             5.0.8
referencing                       0.35.1
regex                             2023.12.25
requests                          2.31.0
requests-file                     2.1.0
requests-oauthlib                 2.0.0
requests-toolbelt                 1.0.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.5.2
rpds-py                           0.20.0
rsa                               4.7.2
ruff                              0.6.5
s3transfer                        0.10.2
safetensors                       0.4.5
scikit-image                      0.21.0
scikit-learn                      1.5.2
scipy                             1.13.1
semantic-version                  2.10.0
Send2Trash                        1.8.3
sentencepiece                     0.2.0
sentry-sdk                        1.43.0
setproctitle                      1.3.3
setuptools                        72.1.0
shapely                           2.0.6
shellingham                       1.5.4
shtab                             1.7.1
simplejson                        3.19.3
six                               1.16.0
skypilot                          0.5.0
smmap                             5.0.1
sniffio                           1.3.1
soupsieve                         2.6
spandrel                          0.4.0
stack-data                        0.6.3
starlette                         0.37.2
structlog                         24.4.0
supervision                       0.22.0
sympy                             1.13.2
tabulate                          0.9.0
tensorboard-data-server           0.6.1
tensorboard-plugin-wit            1.8.1
tensorflow-estimator              2.10.0
tensorflow-io-gcs-filesystem      0.31.0
tensorrt                          8.6.1
tensorrt-cu11                     10.4.0
tensorrt-cu11_bindings            10.4.0
tensorrt-cu11_libs                10.4.0
tensorrt-cu12                     10.4.0
tensorrt-cu12_bindings            10.4.0
tensorrt-cu12_libs                10.4.0
termcolor                         2.4.0
terminado                         0.18.1
threadpoolctl                     3.4.0
tifffile                          2024.2.12
time-machine                      2.15.0
timm                              1.0.12
tinycss2                          1.3.0
tk                                0.1.0
tldextract                        5.1.2
tokenizers                        0.19.1
tomli                             2.0.1
tomlkit                           0.12.0
torch                             2.4.0+cu118
torchaudio                        2.4.0+cu118
torchmetrics                      0.11.4
torchvision                       0.19.0+cu118
tornado                           6.4.1
tqdm                              4.66.4
traitlets                         5.14.3
transformers                      4.44.2
txt2tags                          3.9
typer                             0.9.0
types-python-dateutil             2.9.0.20241003
typing_extensions                 4.12.2
typing-inspect                    0.9.0
tyro                              0.8.5
tzdata                            2024.1
tzlocal                           5.2
uri-template                      1.3.0
uritemplate                       4.1.1
urllib3                           2.2.3
uvicorn                           0.30.6
wandb                             0.15.10
wcwidth                           0.2.13
webcolors                         24.8.0
webencodings                      0.5.1
websocket-client                  1.8.0
websockets                        11.0.3
Werkzeug                          3.0.4
wheel                             0.44.0
widgetsnbextension                4.0.13
wrapt                             1.14.1
yarl                              1.11.1
zipp                              3.21.0
zxing-cpp                         2.2.0

C:\Comfy\ComfyUI_windows_portable\ComfyUI>pip check
gradio 4.44.0 has requirement typer<1.0,>=0.12; sys_platform != "emscripten", but you have typer 0.9.0.

## Execute install/(de)activation script for 'C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use'
[!] WARNING: Ignoring invalid distribution ~ransformers (C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
                                 [!] WARNING: Ignoring invalid distribution ~ransformers (C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
[!] WARNING: Ignoring invalid distribution ~ransformers (C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages)

[ComfyUI-Manager] Startup script completed.
#######################################################################

WARNING: Ignoring invalid distribution ~ransformers (C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages)

Prestartup times for custom nodes:
   0.0 seconds: C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   6.6 seconds: C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 32537 MB
pytorch version: 2.4.1+cu121
C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: C:\Comfy\ComfyUI_windows_portable\ComfyUI\web
C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Web extensions folder found at C:\Comfy\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
Adding C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Loaded AnimateDiff from C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Loaded IPAdapter nodes from C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V7.14)
Loaded ImpactPack nodes from[Impact Pack] Wildcards loading done. C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: 12th Gen Intel(R) Core(TM) i7-12650H - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Laptop GPU
[Crystools INFO] NVIDIA Driver: 565.90
False

===================================BUG REPORT===================================
C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\cuda_setup\main.py:167: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('/hf-mirror.com'), WindowsPath('https')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\__init__.py", line 21, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 17, in <module>
    from .layer_diffuse import LayerDiffuse, LayerMethod
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\layer_diffuse\__init__.py", line 12, in <module>
    from .model import ModelPatcher, TransparentVAEDecoder, calculate_weight_adjust_channel
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\layer_diffuse\model.py", line 17, in <module>
    from diffusers.models.modeling_utils import ModelMixin
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 35, in <module>
    from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\quantizers\__init__.py", line 15, in <module>
    from .auto import DiffusersAutoQuantizer
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\quantizers\auto.py", line 21, in <module>
    from .bitsandbytes import BnB4BitDiffusersQuantizer, BnB8BitDiffusersQuantizer
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\quantizers\bitsandbytes\__init__.py", line 2, in <module>
    from .utils import dequantize_and_replace, dequantize_bnb_weight, replace_with_bnb_linear
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\quantizers\bitsandbytes\utils.py", line 32, in <module>
    import bitsandbytes as bnb
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

Cannot import C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use module for custom nodes:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

   0.2 seconds (IMPORT FAILED): C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use

**Comment by anseltrust** [comment]
I appreciate any help:)

**Comment by whitesky1226** [comment]
After updating Comfy, I couldn't load Easy-Use nodes either. 
I tried to upgrade pytorch to 2.5.1 with CUDA 12.4 (https://pytorch.org/), and upgraded xformers (https://github.com/facebookresearch/xformers?tab=readme-ov-file#installing-xformers) then reloaded Comfy. DONE!🤓

**Comment by Talae06** [comment]
Import failing for me too, whereas everything is up to date, including torch and xformers.

**Comment by anseltrust** [comment]
> Import failing for me too, whereas everything is up to date, including torch and xformers. EDIT : nevermind, found out after disabling all custom nodes that my ComfyUI install had a problem. The culprit was the transformers package which had been upgraded to 4.47 for some reason. Solved the problem by downgrading it to the version just before, 4.46.3.

The fresh reinstallation of ComfyUI and ComfyUI Manager together did solve the issue for me, Follow the installation method 3;

https://github.com/ltdrdata/ComfyUI-Manager

**Comment by NetAndif** [comment]
> Import failing for me too, whereas everything is up to date, including torch and xformers. EDIT : nevermind, found out after disabling all custom nodes that my ComfyUI install had a problem. The culprit was the transformers package which had been upgraded to 4.47 for some reason. Solved the problem by downgrading it to the version just before, 4.46.3.

I've downgraded transformers to 4.46.3 and that fixed it for me, too. Thanks for the hint!
Btw "ltx-video" requires 4.47 - however, I wanted to get rid of that anyways.

**Comment by Talae06** [comment]
I know it's an old thread, but since I still had the same problem with recent versions of transformers, which every update of ComfyUI installed and thus I had to downgrade the package each time... I finally managed to solve the issue (once and for all, hopefully) thanks to [this thread](https://github.com/yolain/ComfyUI-Easy-Use/issues/610#issuecomment-2581689753) (and Google Translate).
Updating the peft package to 0.14.0 did actually eliminate the problem with versions of transformers more recent than 4.46.3. Leaving it here in case it might be useful to others !
